#!/bin/bash

if [ $# != 1 ]
then
    echo USAGE: electron-ng project-name
else
    echo "mkdir $1"
    mkdir $1
    cd $1
    echo "create electron template project"
    npm init
    mkdir dist
    echo -e "const electron = require('electron')
const { BrowserWindow } = require('electron')
const app = electron.app;

function createAppWindow() {

  const window = new BrowserWindow({
    width: 800,
    height: 600
});
// window.setSize(1000,800);
window.loadFile(\"dist/index.html\");
// window.openDevTools();

}
app.on('ready', createAppWindow)" > index.js
    sed -i "s#\"scripts\": {#\"scripts\": {\n\t\t\"start\":\"electron .\",#" package.json  
    echo "create angular template project"
    mkdir "angular"
    cd "angular"
    ng new $1
    cd $1
    sed -i "s#dist/$1#../../dist#" angular.json 
    sed -i "s#<base href=\"\/\">##" src/index.html
    ng build
    cd ../..
    electron . &
fi
